spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 20
      auto-commit: true
      pool-name: MyhikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:mysql://192.168.228.129:3306/decoratestate?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: you127318
mybatis-plus:
  type-aliases-package: com.youhopefly.smp.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8888
  servlet:
    context-path: /smp